DROP SEQUENCE WORKSPACEMEMBERSEQ;
DROP TABLE WORKSPACEMEMBER;

CREATE SEQUENCE WORKSPACEMEMBERSEQ;
CREATE TABLE WORKSPACEMEMBER (
	
	WORKSPACEMEMBER_SEQ 	INT 				PRIMARY KEY,
	WORKSPACE_SEQ 			INT 				NOT NULL,
	WORKSPACE_NAME 			VARCHAR2(100) 		NOT NULL,
	MEMBER_ID				VARCHAR2(50)		NOT NULL,
	MEMBER_NAME 			VARCHAR2(20)	 	NOT NULL,
	WORKSPACE_REGDATE		DATE 				NOT NULL

);

INSERT INTO WORKSPACEMEMBER
VALUES (WORKSPACEMEMBERSEQ.NEXTVAL, 1, 'KH정보교육원', 'kh', 'kh', SYSDATE);

INSERT INTO WORKSPACEMEMBER
VALUES (WORKSPACEMEMBERSEQ.NEXTVAL, 2, 'KH세미프로젝트', 'kh', 'kh', SYSDATE);

INSERT INTO WORKSPACEMEMBER
VALUES (WORKSPACEMEMBERSEQ.NEXTVAL, 3, 'KH파이널프로젝트', 'kh', 'kh', SYSDATE);

INSERT INTO WORKSPACEMEMBER
VALUES (WORKSPACEMEMBERSEQ.NEXTVAL, 1, 'KH정보교육원', 'tt', 'tt', SYSDATE);

INSERT INTO WORKSPACEMEMBER
VALUES (WORKSPACEMEMBERSEQ.NEXTVAL, 2, 'KH세미프로젝트', 'tt', 'tt', SYSDATE);

INSERT INTO WORKSPACEMEMBER
VALUES (WORKSPACEMEMBERSEQ.NEXTVAL, 3, 'KH파이널프로젝트', 'tt', 'tt', SYSDATE);

SELECT * FROM WORKSPACEMEMBER
WHERE MEMBER_ID = 'tt'
ORDER BY WORKSPACEMEMBER_SEQ;

UPDATE WORKSPACEMEMBER
SET WORKSPACE_SEQ = 5
WHERE WORKSPACE_SEQ = 0;

DELETE FROM WORKSPACEMEMBER WHERE WORKSPACE_SEQ = 4;

